//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Microsoft.Crm.Sdk.Samples.ParsingService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ParsingServiceSoap", Namespace="http://services.resumeparsing.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseRequest))]
    public partial class ParsingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ParseResumeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParseJobOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback NormalizeResumeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ParsingService() {
            this.Url = global::Microsoft.Crm.Sdk.Samples.Properties.Settings.Default.SamplePlugins_ParsingService1_ParsingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ParseResumeCompletedEventHandler ParseResumeCompleted;
        
        /// <remarks/>
        public event GetAccountInfoCompletedEventHandler GetAccountInfoCompleted;
        
        /// <remarks/>
        public event ParseJobOrderCompletedEventHandler ParseJobOrderCompleted;
        
        /// <remarks/>
        public event SetDataCompletedEventHandler SetDataCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event ListDataCompletedEventHandler ListDataCompleted;
        
        /// <remarks/>
        public event DeleteDataCompletedEventHandler DeleteDataCompleted;
        
        /// <remarks/>
        public event NormalizeResumeCompletedEventHandler NormalizeResumeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/ParseResume", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParseResumeResponse ParseResume(ParseResumeRequest request) {
            object[] results = this.Invoke("ParseResume", new object[] {
                        request});
            return ((ParseResumeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ParseResumeAsync(ParseResumeRequest request) {
            this.ParseResumeAsync(request, null);
        }
        
        /// <remarks/>
        public void ParseResumeAsync(ParseResumeRequest request, object userState) {
            if ((this.ParseResumeOperationCompleted == null)) {
                this.ParseResumeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParseResumeOperationCompleted);
            }
            this.InvokeAsync("ParseResume", new object[] {
                        request}, this.ParseResumeOperationCompleted, userState);
        }
        
        private void OnParseResumeOperationCompleted(object arg) {
            if ((this.ParseResumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParseResumeCompleted(this, new ParseResumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/GetAccountInfo", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetAccountInfoResponse GetAccountInfo(GetAccountInfoRequest request) {
            object[] results = this.Invoke("GetAccountInfo", new object[] {
                        request});
            return ((GetAccountInfoResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(GetAccountInfoRequest request) {
            this.GetAccountInfoAsync(request, null);
        }
        
        /// <remarks/>
        public void GetAccountInfoAsync(GetAccountInfoRequest request, object userState) {
            if ((this.GetAccountInfoOperationCompleted == null)) {
                this.GetAccountInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountInfoOperationCompleted);
            }
            this.InvokeAsync("GetAccountInfo", new object[] {
                        request}, this.GetAccountInfoOperationCompleted, userState);
        }
        
        private void OnGetAccountInfoOperationCompleted(object arg) {
            if ((this.GetAccountInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountInfoCompleted(this, new GetAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/ParseJobOrder", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ParseJobOrderResponse ParseJobOrder(ParseJobOrderRequest request) {
            object[] results = this.Invoke("ParseJobOrder", new object[] {
                        request});
            return ((ParseJobOrderResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ParseJobOrderAsync(ParseJobOrderRequest request) {
            this.ParseJobOrderAsync(request, null);
        }
        
        /// <remarks/>
        public void ParseJobOrderAsync(ParseJobOrderRequest request, object userState) {
            if ((this.ParseJobOrderOperationCompleted == null)) {
                this.ParseJobOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParseJobOrderOperationCompleted);
            }
            this.InvokeAsync("ParseJobOrder", new object[] {
                        request}, this.ParseJobOrderOperationCompleted, userState);
        }
        
        private void OnParseJobOrderOperationCompleted(object arg) {
            if ((this.ParseJobOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParseJobOrderCompleted(this, new ParseJobOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/SetData", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SetDataResponse SetData(SetDataRequest request) {
            object[] results = this.Invoke("SetData", new object[] {
                        request});
            return ((SetDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetDataAsync(SetDataRequest request) {
            this.SetDataAsync(request, null);
        }
        
        /// <remarks/>
        public void SetDataAsync(SetDataRequest request, object userState) {
            if ((this.SetDataOperationCompleted == null)) {
                this.SetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDataOperationCompleted);
            }
            this.InvokeAsync("SetData", new object[] {
                        request}, this.SetDataOperationCompleted, userState);
        }
        
        private void OnSetDataOperationCompleted(object arg) {
            if ((this.SetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDataCompleted(this, new SetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/GetData", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetDataResponse GetData(GetDataRequest request) {
            object[] results = this.Invoke("GetData", new object[] {
                        request});
            return ((GetDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(GetDataRequest request) {
            this.GetDataAsync(request, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(GetDataRequest request, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        request}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/ListData", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListDataResponse ListData(ListDataRequest request) {
            object[] results = this.Invoke("ListData", new object[] {
                        request});
            return ((ListDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ListDataAsync(ListDataRequest request) {
            this.ListDataAsync(request, null);
        }
        
        /// <remarks/>
        public void ListDataAsync(ListDataRequest request, object userState) {
            if ((this.ListDataOperationCompleted == null)) {
                this.ListDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListDataOperationCompleted);
            }
            this.InvokeAsync("ListData", new object[] {
                        request}, this.ListDataOperationCompleted, userState);
        }
        
        private void OnListDataOperationCompleted(object arg) {
            if ((this.ListDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListDataCompleted(this, new ListDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/DeleteData", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeleteDataResponse DeleteData(DeleteDataRequest request) {
            object[] results = this.Invoke("DeleteData", new object[] {
                        request});
            return ((DeleteDataResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteDataAsync(DeleteDataRequest request) {
            this.DeleteDataAsync(request, null);
        }
        
        /// <remarks/>
        public void DeleteDataAsync(DeleteDataRequest request, object userState) {
            if ((this.DeleteDataOperationCompleted == null)) {
                this.DeleteDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteDataOperationCompleted);
            }
            this.InvokeAsync("DeleteData", new object[] {
                        request}, this.DeleteDataOperationCompleted, userState);
        }
        
        private void OnDeleteDataOperationCompleted(object arg) {
            if ((this.DeleteDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteDataCompleted(this, new DeleteDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.resumeparsing.com/NormalizeResume", RequestNamespace="http://services.resumeparsing.com/", ResponseNamespace="http://services.resumeparsing.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NormalizeResumeResponse NormalizeResume(NormalizeResumeRequest request) {
            object[] results = this.Invoke("NormalizeResume", new object[] {
                        request});
            return ((NormalizeResumeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void NormalizeResumeAsync(NormalizeResumeRequest request) {
            this.NormalizeResumeAsync(request, null);
        }
        
        /// <remarks/>
        public void NormalizeResumeAsync(NormalizeResumeRequest request, object userState) {
            if ((this.NormalizeResumeOperationCompleted == null)) {
                this.NormalizeResumeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNormalizeResumeOperationCompleted);
            }
            this.InvokeAsync("NormalizeResume", new object[] {
                        request}, this.NormalizeResumeOperationCompleted, userState);
        }
        
        private void OnNormalizeResumeOperationCompleted(object arg) {
            if ((this.NormalizeResumeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NormalizeResumeCompleted(this, new NormalizeResumeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeRequest {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        private byte[] fileBytesField;
        
        private string fileTextField;
        
        private string configurationField;
        
        private System.Nullable<bool> outputXmlDocField;
        
        private System.Nullable<bool> outputHtmlField;
        
        private System.Nullable<bool> outputRtfField;
        
        private System.Nullable<bool> outputWordXmlField;
        
        private string revisionDateField;
        
        private string parserVersionField;
        
        private string skillsDataField;
        
        private string normalizerDataField;
        
        private System.Nullable<bool> outputPdfField;
        
        private System.Nullable<bool> outputCandidateImageField;
        
        private System.Nullable<bool> outputJsonField;
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileBytes {
            get {
                return this.fileBytesField;
            }
            set {
                this.fileBytesField = value;
            }
        }
        
        /// <remarks/>
        public string FileText {
            get {
                return this.fileTextField;
            }
            set {
                this.fileTextField = value;
            }
        }
        
        /// <remarks/>
        public string Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputXmlDoc {
            get {
                return this.outputXmlDocField;
            }
            set {
                this.outputXmlDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputHtml {
            get {
                return this.outputHtmlField;
            }
            set {
                this.outputHtmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputRtf {
            get {
                return this.outputRtfField;
            }
            set {
                this.outputRtfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputWordXml {
            get {
                return this.outputWordXmlField;
            }
            set {
                this.outputWordXmlField = value;
            }
        }
        
        /// <remarks/>
        public string RevisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
            }
        }
        
        /// <remarks/>
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        public string SkillsData {
            get {
                return this.skillsDataField;
            }
            set {
                this.skillsDataField = value;
            }
        }
        
        /// <remarks/>
        public string NormalizerData {
            get {
                return this.normalizerDataField;
            }
            set {
                this.normalizerDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputPdf {
            get {
                return this.outputPdfField;
            }
            set {
                this.outputPdfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputCandidateImage {
            get {
                return this.outputCandidateImageField;
            }
            set {
                this.outputCandidateImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputJson {
            get {
                return this.outputJsonField;
            }
            set {
                this.outputJsonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class Data {
        
        private string keyField;
        
        private string nameField;
        
        private string typeField;
        
        private string cultureField;
        
        private string timestampField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        public string Timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NormalizeResumeResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDataResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetDataResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class BaseResponse {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class NormalizeResumeResponse : BaseResponse {
        
        private string xmlField;
        
        private int creditsRemainingField;
        
        private string normalizerVersionField;
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        public string NormalizerVersion {
            get {
                return this.normalizerVersionField;
            }
            set {
                this.normalizerVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class DeleteDataResponse : BaseResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ListDataResponse : BaseResponse {
        
        private Data[] dataListField;
        
        /// <remarks/>
        public Data[] DataList {
            get {
                return this.dataListField;
            }
            set {
                this.dataListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetDataResponse : BaseResponse {
        
        private string[] contentField;
        
        private byte[] contentBytesField;
        
        /// <remarks/>
        public string[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ContentBytes {
            get {
                return this.contentBytesField;
            }
            set {
                this.contentBytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class SetDataResponse : BaseResponse {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NormalizeResumeRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDataRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetDataRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class BaseRequest {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class NormalizeResumeRequest : BaseRequest {
        
        private string xmlField;
        
        private string normalizerDataField;
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        public string NormalizerData {
            get {
                return this.normalizerDataField;
            }
            set {
                this.normalizerDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class DeleteDataRequest : BaseRequest {
        
        private string typeField;
        
        private string nameField;
        
        private string cultureField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ListDataRequest : BaseRequest {
        
        private string typeField;
        
        private string cultureField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetDataRequest : BaseRequest {
        
        private string nameField;
        
        private string cultureField;
        
        private string typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class SetDataRequest : BaseRequest {
        
        private string typeField;
        
        private string nameField;
        
        private string cultureField;
        
        private string[] contentField;
        
        private byte[] contentBytesField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        public string[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] ContentBytes {
            get {
                return this.contentBytesField;
            }
            set {
                this.contentBytesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderResponse {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string fileTypeField;
        
        private string textField;
        
        private string textCodeField;
        
        private string xmlField;
        
        private System.Xml.XmlNode xmlDocField;
        
        private string htmlField;
        
        private string htmlCodeField;
        
        private string rtfField;
        
        private string rtfCodeField;
        
        private string wordXmlField;
        
        private string wordXmlCodeField;
        
        private int creditsRemainingField;
        
        private string parserVersionField;
        
        private string fileExtensionField;
        
        private byte[] pdfField;
        
        private string pdfCodeField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string TextCode {
            get {
                return this.textCodeField;
            }
            set {
                this.textCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode XmlDoc {
            get {
                return this.xmlDocField;
            }
            set {
                this.xmlDocField = value;
            }
        }
        
        /// <remarks/>
        public string Html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        public string HtmlCode {
            get {
                return this.htmlCodeField;
            }
            set {
                this.htmlCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Rtf {
            get {
                return this.rtfField;
            }
            set {
                this.rtfField = value;
            }
        }
        
        /// <remarks/>
        public string RtfCode {
            get {
                return this.rtfCodeField;
            }
            set {
                this.rtfCodeField = value;
            }
        }
        
        /// <remarks/>
        public string WordXml {
            get {
                return this.wordXmlField;
            }
            set {
                this.wordXmlField = value;
            }
        }
        
        /// <remarks/>
        public string WordXmlCode {
            get {
                return this.wordXmlCodeField;
            }
            set {
                this.wordXmlCodeField = value;
            }
        }
        
        /// <remarks/>
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        public string PdfCode {
            get {
                return this.pdfCodeField;
            }
            set {
                this.pdfCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderConfiguration {
        
        private string countryCodeField;
        
        private string languageField;
        
        private string knownTypeField;
        
        private bool includeRecruitingTermsField;
        
        private bool includeSupplementalTextField;
        
        private bool preferShorterJobTitlesField;
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string KnownType {
            get {
                return this.knownTypeField;
            }
            set {
                this.knownTypeField = value;
            }
        }
        
        /// <remarks/>
        public bool IncludeRecruitingTerms {
            get {
                return this.includeRecruitingTermsField;
            }
            set {
                this.includeRecruitingTermsField = value;
            }
        }
        
        /// <remarks/>
        public bool IncludeSupplementalText {
            get {
                return this.includeSupplementalTextField;
            }
            set {
                this.includeSupplementalTextField = value;
            }
        }
        
        /// <remarks/>
        public bool PreferShorterJobTitles {
            get {
                return this.preferShorterJobTitlesField;
            }
            set {
                this.preferShorterJobTitlesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseJobOrderRequest {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        private byte[] fileBytesField;
        
        private string fileTextField;
        
        private ParseJobOrderConfiguration configurationField;
        
        private System.Nullable<bool> outputXmlDocField;
        
        private System.Nullable<bool> outputHtmlField;
        
        private System.Nullable<bool> outputRtfField;
        
        private System.Nullable<bool> outputWordXmlField;
        
        private string revisionDateField;
        
        private string parserVersionField;
        
        private string skillsDataField;
        
        private string normalizerDataField;
        
        private System.Nullable<bool> outputPdfField;
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileBytes {
            get {
                return this.fileBytesField;
            }
            set {
                this.fileBytesField = value;
            }
        }
        
        /// <remarks/>
        public string FileText {
            get {
                return this.fileTextField;
            }
            set {
                this.fileTextField = value;
            }
        }
        
        /// <remarks/>
        public ParseJobOrderConfiguration Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputXmlDoc {
            get {
                return this.outputXmlDocField;
            }
            set {
                this.outputXmlDocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputHtml {
            get {
                return this.outputHtmlField;
            }
            set {
                this.outputHtmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputRtf {
            get {
                return this.outputRtfField;
            }
            set {
                this.outputRtfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputWordXml {
            get {
                return this.outputWordXmlField;
            }
            set {
                this.outputWordXmlField = value;
            }
        }
        
        /// <remarks/>
        public string RevisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
            }
        }
        
        /// <remarks/>
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        public string SkillsData {
            get {
                return this.skillsDataField;
            }
            set {
                this.skillsDataField = value;
            }
        }
        
        /// <remarks/>
        public string NormalizerData {
            get {
                return this.normalizerDataField;
            }
            set {
                this.normalizerDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OutputPdf {
            get {
                return this.outputPdfField;
            }
            set {
                this.outputPdfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoResponse {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private int creditsUsedField;
        
        private int creditsRemainingField;
        
        private string expirationDateField;
        
        private int maximumConcurrentRequestsField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public int CreditsUsed {
            get {
                return this.creditsUsedField;
            }
            set {
                this.creditsUsedField = value;
            }
        }
        
        /// <remarks/>
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public int MaximumConcurrentRequests {
            get {
                return this.maximumConcurrentRequestsField;
            }
            set {
                this.maximumConcurrentRequestsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoRequest {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        /// <remarks/>
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeResponse {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string fileTypeField;
        
        private string textField;
        
        private string textCodeField;
        
        private string xmlField;
        
        private System.Xml.XmlNode xmlDocField;
        
        private string htmlField;
        
        private string htmlCodeField;
        
        private string rtfField;
        
        private string rtfCodeField;
        
        private string wordXmlField;
        
        private string wordXmlCodeField;
        
        private int creditsRemainingField;
        
        private string parserVersionField;
        
        private string fileExtensionField;
        
        private byte[] pdfField;
        
        private string pdfCodeField;
        
        private byte[] candidateImageField;
        
        private string candidateImageExtensionField;
        
        private string jsonField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string TextCode {
            get {
                return this.textCodeField;
            }
            set {
                this.textCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode XmlDoc {
            get {
                return this.xmlDocField;
            }
            set {
                this.xmlDocField = value;
            }
        }
        
        /// <remarks/>
        public string Html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
            }
        }
        
        /// <remarks/>
        public string HtmlCode {
            get {
                return this.htmlCodeField;
            }
            set {
                this.htmlCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Rtf {
            get {
                return this.rtfField;
            }
            set {
                this.rtfField = value;
            }
        }
        
        /// <remarks/>
        public string RtfCode {
            get {
                return this.rtfCodeField;
            }
            set {
                this.rtfCodeField = value;
            }
        }
        
        /// <remarks/>
        public string WordXml {
            get {
                return this.wordXmlField;
            }
            set {
                this.wordXmlField = value;
            }
        }
        
        /// <remarks/>
        public string WordXmlCode {
            get {
                return this.wordXmlCodeField;
            }
            set {
                this.wordXmlCodeField = value;
            }
        }
        
        /// <remarks/>
        public int CreditsRemaining {
            get {
                return this.creditsRemainingField;
            }
            set {
                this.creditsRemainingField = value;
            }
        }
        
        /// <remarks/>
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
            }
        }
        
        /// <remarks/>
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        public string PdfCode {
            get {
                return this.pdfCodeField;
            }
            set {
                this.pdfCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] CandidateImage {
            get {
                return this.candidateImageField;
            }
            set {
                this.candidateImageField = value;
            }
        }
        
        /// <remarks/>
        public string CandidateImageExtension {
            get {
                return this.candidateImageExtensionField;
            }
            set {
                this.candidateImageExtensionField = value;
            }
        }
        
        /// <remarks/>
        public string Json {
            get {
                return this.jsonField;
            }
            set {
                this.jsonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ParseResumeCompletedEventHandler(object sender, ParseResumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParseResumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParseResumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParseResumeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParseResumeResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetAccountInfoCompletedEventHandler(object sender, GetAccountInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAccountInfoResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAccountInfoResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ParseJobOrderCompletedEventHandler(object sender, ParseJobOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParseJobOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParseJobOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ParseJobOrderResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ParseJobOrderResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetDataCompletedEventHandler(object sender, SetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListDataCompletedEventHandler(object sender, ListDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteDataCompletedEventHandler(object sender, DeleteDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeleteDataResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeleteDataResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void NormalizeResumeCompletedEventHandler(object sender, NormalizeResumeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NormalizeResumeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NormalizeResumeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NormalizeResumeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NormalizeResumeResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591