//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseResume.ResumeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.resumeparsing.com/", ConfigurationName="ResumeService.ResumeServiceSoap")]
    public interface ResumeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/ParseResume", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParseResume.ResumeService.ParseResumeResponse ParseResume(ParseResume.ResumeService.ParseResumeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.resumeparsing.com/GetAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParseResume.ResumeService.GetAccountInfoResponse GetAccountInfo(ParseResume.ResumeService.GetAccountInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        private byte[] fileBytesField;
        
        private string fileTextField;
        
        private string configurationField;
        
        private System.Nullable<bool> outputXmlDocField;
        
        private System.Nullable<bool> outputHtmlField;
        
        private System.Nullable<bool> outputRtfField;
        
        private System.Nullable<bool> outputWordXmlField;
        
        private string revisionDateField;
        
        private string parserVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] FileBytes {
            get {
                return this.fileBytesField;
            }
            set {
                this.fileBytesField = value;
                this.RaisePropertyChanged("FileBytes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileText {
            get {
                return this.fileTextField;
            }
            set {
                this.fileTextField = value;
                this.RaisePropertyChanged("FileText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("Configuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<bool> OutputXmlDoc {
            get {
                return this.outputXmlDocField;
            }
            set {
                this.outputXmlDocField = value;
                this.RaisePropertyChanged("OutputXmlDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> OutputHtml {
            get {
                return this.outputHtmlField;
            }
            set {
                this.outputHtmlField = value;
                this.RaisePropertyChanged("OutputHtml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> OutputRtf {
            get {
                return this.outputRtfField;
            }
            set {
                this.outputRtfField = value;
                this.RaisePropertyChanged("OutputRtf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> OutputWordXml {
            get {
                return this.outputWordXmlField;
            }
            set {
                this.outputWordXmlField = value;
                this.RaisePropertyChanged("OutputWordXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RevisionDate {
            get {
                return this.revisionDateField;
            }
            set {
                this.revisionDateField = value;
                this.RaisePropertyChanged("RevisionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
                this.RaisePropertyChanged("ParserVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private int totalTransactionsField;
        
        private int transactionsRemainingField;
        
        private string expirationDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalTransactions {
            get {
                return this.totalTransactionsField;
            }
            set {
                this.totalTransactionsField = value;
                this.RaisePropertyChanged("TotalTransactions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TransactionsRemaining {
            get {
                return this.transactionsRemainingField;
            }
            set {
                this.transactionsRemainingField = value;
                this.RaisePropertyChanged("TransactionsRemaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class GetAccountInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string serviceKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceKey {
            get {
                return this.serviceKeyField;
            }
            set {
                this.serviceKeyField = value;
                this.RaisePropertyChanged("ServiceKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.resumeparsing.com/")]
    public partial class ParseResumeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string subCodeField;
        
        private string messageField;
        
        private string fileTypeField;
        
        private string textField;
        
        private string textCodeField;
        
        private string xmlField;
        
        private System.Xml.XmlNode xmlDocField;
        
        private string htmlField;
        
        private string htmlCodeField;
        
        private string rtfField;
        
        private string rtfCodeField;
        
        private string wordXmlField;
        
        private string wordXmlCodeField;
        
        private int usesRemainingField;

        //Added custom field
        public int CreditsRemaining;
        
        private string parserVersionField;
        
        private string fileExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("SubCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
                this.RaisePropertyChanged("FileType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TextCode {
            get {
                return this.textCodeField;
            }
            set {
                this.textCodeField = value;
                this.RaisePropertyChanged("TextCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
                this.RaisePropertyChanged("Xml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Xml.XmlNode XmlDoc {
            get {
                return this.xmlDocField;
            }
            set {
                this.xmlDocField = value;
                this.RaisePropertyChanged("XmlDoc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Html {
            get {
                return this.htmlField;
            }
            set {
                this.htmlField = value;
                this.RaisePropertyChanged("Html");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HtmlCode {
            get {
                return this.htmlCodeField;
            }
            set {
                this.htmlCodeField = value;
                this.RaisePropertyChanged("HtmlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Rtf {
            get {
                return this.rtfField;
            }
            set {
                this.rtfField = value;
                this.RaisePropertyChanged("Rtf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RtfCode {
            get {
                return this.rtfCodeField;
            }
            set {
                this.rtfCodeField = value;
                this.RaisePropertyChanged("RtfCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string WordXml {
            get {
                return this.wordXmlField;
            }
            set {
                this.wordXmlField = value;
                this.RaisePropertyChanged("WordXml");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string WordXmlCode {
            get {
                return this.wordXmlCodeField;
            }
            set {
                this.wordXmlCodeField = value;
                this.RaisePropertyChanged("WordXmlCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int UsesRemaining {
            get {
                return this.usesRemainingField;
            }
            set {
                this.usesRemainingField = value;
                this.RaisePropertyChanged("UsesRemaining");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ParserVersion {
            get {
                return this.parserVersionField;
            }
            set {
                this.parserVersionField = value;
                this.RaisePropertyChanged("ParserVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
                this.RaisePropertyChanged("FileExtension");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ResumeServiceSoapChannel : ParseResume.ResumeService.ResumeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResumeServiceSoapClient : System.ServiceModel.ClientBase<ParseResume.ResumeService.ResumeServiceSoap>, ParseResume.ResumeService.ResumeServiceSoap {
        
        public ResumeServiceSoapClient() {
        }
        
        public ResumeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResumeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResumeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResumeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ParseResume.ResumeService.ParseResumeResponse ParseResume(ParseResume.ResumeService.ParseResumeRequest request) {
            return base.Channel.ParseResume(request);
        }
        
        public ParseResume.ResumeService.GetAccountInfoResponse GetAccountInfo(ParseResume.ResumeService.GetAccountInfoRequest request) {
            return base.Channel.GetAccountInfo(request);
        }
    }
}
